version: "3.9"

services:
  backend:
    build: ./backproywebai
    container_name: backend_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backproywebai:/app
    env_file:
      - ./.env
    restart: always

  frontend:
    build: ./proywebai
    container_name: frontend_react
    ports:
      - "3000:80"
    restart: always
